import type { Lang } from '@/app/lib/dict'

// Contenido de las páginas dedicadas por función de Vanty ABA
export const FEAT: Record<Lang, any> = {
  es: {
    feat: {
      gridTitle: 'Cada función, a fondo',
      gridLead: 'Conoce en detalle todo lo que Vanty ABA hace por tu centro.',
      conocer: 'Ver detalle', back: 'Volver a Vanty ABA',
      benefitsTitle: 'Beneficios', practiceTitle: 'En la práctica',
      forWhomTitle: '¿Para quién es?', subTitle: 'Todo lo que incluye',
      subLead: 'Funciones pensadas para el día a día clínico.', ctaTitle: 'Veámoslo en tu centro',
      items: {
        aria: {
          name: 'ARIA · Copiloto IA', short: 'Asistentes de IA que generan notas, reportes y alertas en segundos.',
          eyebrow: 'Inteligencia clínica', title: 'ARIA, la IA clínica que trabaja por tu equipo',
          lead: 'Más que un chatbot: ARIA es la inteligencia clínica de Vanty ABA, entrenada en el flujo real de un centro. Redacta notas, ordena reportes, revisa la documentación y anticipa lo que importa — para devolverle a tus terapeutas las horas que el papeleo les quita.',
          deep: 'ARIA aprende cómo trabaja tu centro y asume la parte repetitiva del día a día clínico. Genera notas de sesión y reportes listos para supervisión en segundos, detecta vacíos antes de que se conviertan en un problema y propone objetivos por dominio para cada paciente. Tu equipo recupera horas cada semana y mantiene un estándar clínico impecable, sin esfuerzo extra.',
          points: [
            { icon: 'fileText', t: 'Notas y reportes en segundos', d: 'ARIA convierte cada sesión en notas y reportes clínicos completos al instante, listos para supervisión.' },
            { icon: 'target', t: 'Objetivos sugeridos por dominio', d: 'Propone y evalúa objetivos ABA personalizados para cada paciente, a partir de sus datos reales.' },
            { icon: 'activity', t: 'Patrones y alertas tempranas', d: 'Encuentra tendencias en los datos de sesión y te avisa de riesgos antes de que ocurran.' },
          ],
          forWhom: 'Para terapeutas y analistas que quieren dedicar su tiempo a los pacientes y no al papeleo, y para la supervisión clínica que necesita documentación confiable y siempre al día.',
          roles: ['Terapeutas y especialistas', 'Analistas y supervisión', 'Dirección clínica'],
          sub: [
            { icon: 'fileText', t: 'Notas clínicas automáticas', d: 'Tus sesiones convertidas en notas y reportes profesionales, sin escribir desde cero.' },
            { icon: 'target', t: 'Objetivos a la medida del paciente', d: 'Sugerencias y evaluación de objetivos ABA por dominio, basadas en datos reales.' },
            { icon: 'shieldCheck', t: 'Control de calidad documental', d: 'ARIA revisa tu documentación y te avisa lo que falta, para que nada se escape.' },
            { icon: 'bookOpen', t: 'Tu conocimiento, siempre a mano', d: 'Una base de conocimiento clínico que responde tus dudas al instante, cuando la necesitas.' },
          ],
          benefits: ['Recupera horas clínicas cada semana', 'Documentación impecable y consistente', 'Menos agotamiento para tu equipo', 'Decisiones clínicas con respaldo de datos'],
          quote: 'Antes pasaba horas escribiendo reportes. Con ARIA los tengo en minutos y mi cabeza está donde debe estar: en mis pacientes.',
          quoteRole: 'Analista ABA · Lima, Perú',
          ctaSub: 'Te mostramos a ARIA trabajando con el flujo real de tu centro.',
        },
        analitica: {
          name: 'Analítica y reportes', short: 'Gráficas de dominio por objetivo y alertas automáticas al ≥80%.',
          eyebrow: 'Datos clínicos', title: 'Analítica que se entiende sola',
          lead: 'Gráficas de dominio por objetivo, generadas automáticamente desde el registro de sesión, con alertas y resúmenes listos para supervisión.',
          deep: 'Cada dato que registras en sesión se convierte automáticamente en gráficas claras por objetivo y dominio. Detectas estancamientos a tiempo, justificas decisiones con evidencia y llegas a cada supervisión con todo listo, sin pasar la noche armando hojas de cálculo.',
          points: [
            { t: 'Gráficos por objetivo y dominio', d: 'Visualiza el progreso de cada paciente sin armar hojas de cálculo.' },
            { t: 'Alertas automáticas', d: 'Avisos cuando un objetivo alcanza ≥80%, para decidir el siguiente paso a tiempo.' },
            { t: 'Reportes listos', d: 'Resúmenes claros para dirección, familias y supervisión clínica.' },
          ],
          forWhom: 'Para supervisores y direcciones que necesitan ver el progreso clínico y operativo de un vistazo y decidir con datos, no con intuición.',
          roles: ['Supervisión clínica', 'Dirección del centro', 'Analistas ABA'],
          sub: [
            { t: 'Gráficos por dominio', d: 'Progreso por objetivo, generado automáticamente.' },
            { t: 'Alertas de metas', d: 'Avisos al alcanzar ≥80% en un objetivo.' },
            { t: 'Resúmenes de supervisión', d: 'Todo listo para cada reunión clínica.' },
            { t: 'Importación de datos', d: 'Trae tu histórico desde Excel sin fricción.' },
          ],
          benefits: ['Visibilidad total del centro', 'Menos trabajo manual', 'Decisiones más rápidas', 'Importación desde Excel'],
          quote: 'Por fin veo el progreso de cada niño de un vistazo, sin pelearme con Excel.',
          quoteRole: 'Supervisora clínica · Centro ABA',
          ctaSub: 'Agenda una demo y mira tus datos cobrar sentido.',
        },
        agenda: {
          name: 'Agenda y calendario', short: 'Sesiones y citas sincronizadas con Google y Outlook.',
          eyebrow: 'Programación', title: 'Agenda inteligente, sin choques',
          lead: 'Coordina sesiones, terapeutas y salas en un calendario claro, sincronizado con Google y Outlook.',
          deep: 'Coordina decenas de sesiones, terapeutas y salas sin choques ni huecos. La agenda se sincroniza con Google y Outlook, envía recordatorios automáticos y deja que las familias reserven con un enlace — menos llamadas, menos ausencias y una semana que por fin cuadra.',
          points: [
            { t: 'Sincronización Google y Outlook', d: 'Tu agenda siempre al día en todas tus herramientas.' },
            { t: 'Vista por terapeuta y paciente', d: 'Organiza la semana completa del centro de un vistazo.' },
            { t: 'Enlace para reservar', d: 'Las familias separan sus citas con un link, sin llamadas.' },
          ],
          forWhom: 'Para secretaría y coordinación que arman la semana del centro, y para familias que quieren reservar sus citas sin tener que llamar.',
          roles: ['Secretaría', 'Coordinación', 'Familias'],
          sub: [
            { t: 'Calendario del centro', d: 'Sesiones, terapeutas y salas en una sola vista.' },
            { t: 'Sincronización', d: 'Conecta con Google Calendar y Outlook.' },
            { t: 'Reserva con enlace', d: 'Las familias agendan con un link.' },
            { t: 'Recordatorios', d: 'Avisos automáticos para reducir ausencias.' },
          ],
          benefits: ['Menos ausencias', 'Cero dobles reservas', 'Coordinación clara', 'Recordatorios automáticos'],
          quote: 'Organizar la semana del centro pasó de ser un dolor de cabeza a tomar minutos.',
          quoteRole: 'Secretaría · Centro de terapias',
          ctaSub: 'Te ayudamos a ordenar la agenda de todo tu centro.',
        },
        pagos: {
          name: 'Facturación y pagos', short: 'Administra pagos, emite comprobantes y reportes financieros.',
          eyebrow: 'Finanzas', title: 'Tus pagos, bajo control',
          lead: 'Administra los pagos de tu centro, emite comprobantes y obtén reportes financieros claros, sin planillas dispersas.',
          deep: 'Lleva el control de cada pago, emite comprobantes en segundos y mira el estado financiero de tu centro en tiempo real. Menos morosidad, cuentas claras y reportes listos para tomar decisiones, sin planillas dispersas ni sorpresas a fin de mes.',
          points: [
            { t: 'Control de pagos', d: 'Registra y da seguimiento a los pagos de cada familia.' },
            { t: 'Comprobantes', d: 'Emite comprobantes ordenados en segundos.' },
            { t: 'Reportes financieros', d: 'Visualiza ingresos y pendientes para tomar mejores decisiones.' },
          ],
          forWhom: 'Para administración y dirección que quieren cuentas claras, menos morosidad y reportes financieros sin esfuerzo manual.',
          roles: ['Administración', 'Dirección', 'Contabilidad'],
          sub: [
            { t: 'Registro de pagos', d: 'Seguimiento por familia y por paciente.' },
            { t: 'Comprobantes', d: 'Emisión ordenada en segundos.' },
            { t: 'Estados de cuenta', d: 'Pendientes e ingresos siempre al día.' },
            { t: 'Reportes financieros', d: 'Visión clara para decidir mejor.' },
          ],
          benefits: ['Menos morosidad', 'Cuentas claras', 'Ahorro de tiempo administrativo', 'Todo en un solo lugar'],
          quote: 'Tengo las cuentas del centro claras y al día, sin perseguir pagos en papelitos.',
          quoteRole: 'Administración · Centro ABA',
          ctaSub: 'Conversemos cómo ordenar la parte financiera de tu centro.',
        },
        evaluaciones: {
          name: 'Evaluaciones + CIE-11', short: 'Evaluaciones iniciales con IA y buscador diagnóstico CIE-11.',
          eyebrow: 'Clínico', title: 'Evaluaciones más rápidas y precisas',
          lead: 'Define los objetivos correctos con mayor rapidez: evaluaciones iniciales asistidas por IA y buscador diagnóstico CIE-11 integrado.',
          deep: 'Realiza evaluaciones iniciales asistidas por IA y encuentra diagnósticos con el buscador CIE-11 integrado. Defines los objetivos correctos desde el primer día, con fichas editables que se adaptan a cada paciente y documentación ordenada para todo el equipo.',
          points: [
            { t: 'Evaluación inicial con IA', d: 'Acelera la planificación de la atención personalizada.' },
            { t: 'Buscador CIE-11', d: 'Encuentra y registra diagnósticos sin salir de la plataforma.' },
            { t: 'Fichas editables', d: 'Adapta cada evaluación a la realidad del paciente.' },
          ],
          forWhom: 'Para terapeutas y analistas que realizan evaluaciones iniciales y necesitan definir objetivos con precisión y rapidez.',
          roles: ['Terapeutas ABA', 'Analistas', 'Supervisión clínica'],
          sub: [
            { t: 'Evaluación con IA', d: 'Acelera la evaluación inicial del paciente.' },
            { t: 'Buscador CIE-11', d: 'Diagnósticos integrados en la plataforma.' },
            { t: 'Fichas editables', d: 'Adapta cada evaluación al caso.' },
            { t: 'Plan de objetivos', d: 'Del diagnóstico al plan, en un solo flujo.' },
          ],
          benefits: ['Planificación más rápida', 'Mayor precisión clínica', 'Documentación ordenada', 'Menos trabajo manual'],
          quote: 'Planifico la atención de un nuevo paciente en mucho menos tiempo y con más seguridad.',
          quoteRole: 'Terapeuta ABA · Centro infantil',
          ctaSub: 'Te mostramos cómo agilizar tus evaluaciones.',
        },
        portal: {
          name: 'Portal familiar', short: 'Las familias ven el progreso y reciben actividades para casa.',
          eyebrow: 'Familias', title: 'La familia, dentro del proceso',
          lead: 'Un portal donde los padres ven el progreso en tiempo real, reciben reportes y actividades, y se comunican con el especialista — con avisos automáticos.',
          deep: 'Las familias dejan de quedarse fuera del proceso. Desde su portal ven el progreso en tiempo real, reciben reportes y actividades para casa, y se comunican con el especialista — con avisos automáticos. Más compromiso de los padres y mejores resultados para el niño.',
          points: [
            { t: 'Progreso en tiempo real', d: 'Las familias siguen los avances de su hijo cuando quieran.' },
            { t: 'Actividades para casa', d: 'Refuerza la terapia con actividades recomendadas.' },
            { t: 'Mensajería con el especialista', d: 'Comunicación cercana sin perder el orden clínico.' },
          ],
          forWhom: 'Para familias que quieren seguir el progreso de su hijo y para el centro que busca más adherencia y mejor comunicación.',
          roles: ['Familias y cuidadores', 'Terapeutas', 'Dirección'],
          sub: [
            { t: 'Progreso en vivo', d: 'Avances del paciente en tiempo real.' },
            { t: 'Actividades en casa', d: 'Refuerzo recomendado para los padres.' },
            { t: 'Reportes para familias', d: 'Resúmenes claros y comprensibles.' },
            { t: 'Avisos y mensajería', d: 'Notificaciones y comunicación directa.' },
          ],
          benefits: ['Familias más comprometidas', 'Mejor adherencia', 'Comunicación clara', 'Avisos automáticos'],
          quote: 'Los papás están más involucrados y tranquilos: ven los avances de su hijo cuando quieren.',
          quoteRole: 'Directora · Centro de terapias',
          ctaSub: 'Agenda una demo del portal familiar.',
        },
        comunicacion: {
          name: 'Comunicación interna', short: 'Chat interno del equipo y notificaciones a las familias.',
          eyebrow: 'Comunicación', title: 'Todo el equipo y las familias, conectados',
          lead: 'Chat interno entre el equipo clínico y notificaciones automáticas a las familias por WhatsApp, sin perder el orden ni la privacidad.',
          deep: 'Deja los chats sueltos y los grupos improvisados. Vanty ABA centraliza la comunicación del equipo y mantiene a las familias informadas con avisos automáticos — recordatorios, reportes y mensajes importantes llegan a tiempo, y todo queda ordenado dentro de la plataforma.',
          points: [
            { t: 'Chat interno', d: 'Conversaciones del equipo por paciente y por área.' },
            { t: 'Notificaciones a familias', d: 'Avisos automáticos por WhatsApp en el momento justo.' },
            { t: 'Todo ordenado', d: 'La comunicación queda ligada al historial clínico.' },
          ],
          forWhom: 'Para equipos que quieren dejar de perder información en chats dispersos y para familias que quieren estar al tanto sin instalar nada nuevo.',
          roles: ['Equipo clínico', 'Secretaría', 'Familias'],
          sub: [
            { t: 'Chat por paciente', d: 'Cada caso, con su hilo de conversación.' },
            { t: 'WhatsApp a familias', d: 'Recordatorios y avisos automáticos.' },
            { t: 'Permisos por rol', d: 'Cada quien ve solo lo que le corresponde.' },
            { t: 'Historial unificado', d: 'Mensajes ligados al expediente clínico.' },
          ],
          benefits: ['Menos malentendidos', 'Familias informadas', 'Comunicación ordenada', 'Privacidad por rol'],
          quote: 'Las familias reciben los avisos automáticos y el equipo dejó de perder mensajes importantes.',
          quoteRole: 'Coordinación · Centro de terapias',
          ctaSub: 'Te mostramos cómo ordenar la comunicación de tu centro.',
        },
        videollamadas: {
          name: 'Videollamadas', short: 'Sesiones remotas en alta calidad, dentro de la misma plataforma.',
          eyebrow: 'Telesalud', title: 'Sesiones remotas, sin salir de Vanty ABA',
          lead: 'Atiende a distancia con videollamadas en alta calidad integradas en la plataforma — sin apps externas ni enlaces dispersos.',
          deep: 'Cuando la familia no puede asistir, la terapia no se detiene. Realiza sesiones remotas en alta calidad desde la misma plataforma donde registras, evalúas y reportas — todo queda conectado al historial del paciente, sin saltar entre herramientas.',
          points: [
            { t: 'Videollamada integrada', d: 'Inicia la sesión remota desde la agenda del paciente.' },
            { t: 'Alta calidad', d: 'Audio y video estables para una sesión fluida.' },
            { t: 'Todo en un lugar', d: 'Registra y reporta sin cambiar de herramienta.' },
          ],
          forWhom: 'Para centros que atienden a familias a distancia o en zonas alejadas, y para terapeutas que combinan sesiones presenciales y remotas.',
          roles: ['Terapeutas', 'Familias', 'Dirección'],
          sub: [
            { t: 'Sesión desde la agenda', d: 'Un clic para iniciar la videollamada.' },
            { t: 'Sin apps externas', d: 'Todo ocurre dentro de Vanty ABA.' },
            { t: 'Ligada al paciente', d: 'La sesión queda en su historial.' },
            { t: 'Registro en vivo', d: 'Toma datos mientras atiendes.' },
          ],
          benefits: ['Más cobertura', 'Menos ausencias', 'Sin herramientas extra', 'Todo conectado'],
          quote: 'Puedo atender a familias que viven lejos sin que pierdan ni una sesión.',
          quoteRole: 'Terapeuta ABA · Centro de terapias',
          ctaSub: 'Agenda una demo de las videollamadas integradas.',
        },
      },
    },
  },

  en: {
    feat: {
      gridTitle: 'Every feature, in depth',
      gridLead: 'See in detail everything Vanty ABA does for your center.',
      conocer: 'See details', back: 'Back to Vanty ABA',
      benefitsTitle: 'Benefits', practiceTitle: 'In practice',
      forWhomTitle: 'Who is it for?', subTitle: 'Everything it includes',
      subLead: 'Features built for the clinical day-to-day.', ctaTitle: 'Let\'s see it in your center',
      items: {
        aria: {
          name: 'ARIA · AI Copilot', short: 'AI assistants that generate notes, reports and alerts in seconds.',
          eyebrow: 'Clinical intelligence', title: 'ARIA, the clinical AI that works for your team',
          lead: 'More than a chatbot: ARIA is the clinical intelligence inside Vanty ABA, trained on the real workflow of a center. It drafts notes, organizes reports, reviews documentation and anticipates what matters — to give your therapists back the hours paperwork takes away.',
          deep: 'ARIA learns how your center works and takes on the repetitive part of clinical day-to-day. It generates supervision-ready session notes and reports in seconds, catches gaps before they become a problem and suggests goals by domain for each patient. Your team wins back hours every week and keeps an impeccable clinical standard, with no extra effort.',
          points: [
            { icon: 'fileText', t: 'Notes and reports in seconds', d: 'ARIA turns every session into complete clinical notes and reports instantly, ready for supervision.' },
            { icon: 'target', t: 'Suggested goals by domain', d: 'Proposes and evaluates personalized ABA goals for each patient, based on their real data.' },
            { icon: 'activity', t: 'Patterns and early alerts', d: 'Finds trends in session data and warns you of risks before they happen.' },
          ],
          forWhom: 'For therapists and analysts who want to spend their time with patients, not on paperwork, and for clinical supervision that needs reliable, always up-to-date documentation.',
          roles: ['Therapists and specialists', 'Analysts and supervision', 'Clinical leadership'],
          sub: [
            { icon: 'fileText', t: 'Automatic clinical notes', d: 'Your sessions turned into professional notes and reports, without writing from scratch.' },
            { icon: 'target', t: 'Goals tailored to each patient', d: 'Suggestions and evaluation of ABA goals by domain, based on real data.' },
            { icon: 'shieldCheck', t: 'Documentation quality control', d: 'ARIA reviews your documentation and flags what\'s missing, so nothing slips through.' },
            { icon: 'bookOpen', t: 'Your knowledge, always at hand', d: 'A clinical knowledge base that answers your questions instantly, when you need it.' },
          ],
          benefits: ['Win back clinical hours every week', 'Impeccable, consistent documentation', 'Less burnout for your team', 'Clinical decisions backed by data'],
          quote: 'I used to spend hours writing reports. With ARIA I have them in minutes and my head is where it belongs: on my patients.',
          quoteRole: 'ABA Analyst · Lima, Peru',
          ctaSub: 'We\'ll show you ARIA working with your center\'s real workflow.',
        },
        analitica: {
          name: 'Analytics and reports', short: 'Domain charts by goal and automatic alerts at ≥80%.',
          eyebrow: 'Clinical data', title: 'Analytics that explain themselves',
          lead: 'Domain charts by goal, generated automatically from session data, with alerts and summaries ready for supervision.',
          deep: 'Every data point you record in session turns automatically into clear charts by goal and domain. Spot plateaus in time, back decisions with evidence and arrive at every supervision with everything ready — no late nights building spreadsheets.',
          points: [
            { t: 'Charts by goal and domain', d: 'See each patient\'s progress without building spreadsheets.' },
            { t: 'Automatic alerts', d: 'Notices when a goal reaches ≥80%, so you decide the next step in time.' },
            { t: 'Ready-made reports', d: 'Clear summaries for management, families and clinical supervision.' },
          ],
          forWhom: 'For supervisors and directors who need to see clinical and operational progress at a glance and decide with data, not intuition.',
          roles: ['Clinical supervision', 'Center management', 'ABA analysts'],
          sub: [
            { t: 'Charts by domain', d: 'Progress by goal, generated automatically.' },
            { t: 'Goal alerts', d: 'Notices when a goal reaches ≥80%.' },
            { t: 'Supervision summaries', d: 'Everything ready for each clinical meeting.' },
            { t: 'Data import', d: 'Bring your history from Excel with no friction.' },
          ],
          benefits: ['Full visibility of the center', 'Less manual work', 'Faster decisions', 'Import from Excel'],
          quote: 'I finally see each child\'s progress at a glance, without fighting Excel.',
          quoteRole: 'Clinical Supervisor · ABA Center',
          ctaSub: 'Book a demo and watch your data make sense.',
        },
        agenda: {
          name: 'Scheduling and calendar', short: 'Sessions and appointments synced with Google and Outlook.',
          eyebrow: 'Scheduling', title: 'Smart scheduling, no clashes',
          lead: 'Coordinate sessions, therapists and rooms in a clear calendar, synced with Google and Outlook.',
          deep: 'Coordinate dozens of sessions, therapists and rooms with no clashes or gaps. The calendar syncs with Google and Outlook, sends automatic reminders and lets families book with a link — fewer calls, fewer no-shows and a week that finally adds up.',
          points: [
            { t: 'Google and Outlook sync', d: 'Your calendar always up to date across all your tools.' },
            { t: 'View by therapist and patient', d: 'Organize the center\'s full week at a glance.' },
            { t: 'Booking link', d: 'Families book their appointments with a link, no calls needed.' },
          ],
          forWhom: 'For front-desk and coordination teams who build the center\'s week, and for families who want to book without calling.',
          roles: ['Front desk', 'Coordination', 'Families'],
          sub: [
            { t: 'Center calendar', d: 'Sessions, therapists and rooms in one view.' },
            { t: 'Sync', d: 'Connects with Google Calendar and Outlook.' },
            { t: 'Booking link', d: 'Families schedule with a link.' },
            { t: 'Reminders', d: 'Automatic notices to reduce no-shows.' },
          ],
          benefits: ['Fewer no-shows', 'Zero double bookings', 'Clear coordination', 'Automatic reminders'],
          quote: 'Organizing the center\'s week went from a headache to taking minutes.',
          quoteRole: 'Front desk · Therapy center',
          ctaSub: 'We\'ll help you organize your whole center\'s schedule.',
        },
        pagos: {
          name: 'Billing and payments', short: 'Manage payments, issue receipts and financial reports.',
          eyebrow: 'Finance', title: 'Your payments, under control',
          lead: 'Manage your center\'s payments, issue receipts and get clear financial reports, without scattered spreadsheets.',
          deep: 'Track every payment, issue receipts in seconds and see your center\'s financial status in real time. Less overdue debt, clear accounts and reports ready for decisions — no scattered spreadsheets and no end-of-month surprises.',
          points: [
            { t: 'Payment control', d: 'Record and track each family\'s payments.' },
            { t: 'Receipts', d: 'Issue tidy receipts in seconds.' },
            { t: 'Financial reports', d: 'See income and pending balances to make better decisions.' },
          ],
          forWhom: 'For administration and directors who want clear accounts, less overdue debt and effortless financial reports.',
          roles: ['Administration', 'Management', 'Accounting'],
          sub: [
            { t: 'Payment records', d: 'Tracking by family and by patient.' },
            { t: 'Receipts', d: 'Tidy issuance in seconds.' },
            { t: 'Statements', d: 'Pending and income always up to date.' },
            { t: 'Financial reports', d: 'A clear view to decide better.' },
          ],
          benefits: ['Less overdue debt', 'Clear accounts', 'Saved admin time', 'Everything in one place'],
          quote: 'My center\'s accounts are clear and up to date, no chasing payments on sticky notes.',
          quoteRole: 'Administration · ABA Center',
          ctaSub: 'Let\'s talk about organizing your center\'s finances.',
        },
        evaluaciones: {
          name: 'Assessments + ICD-11', short: 'AI-assisted initial assessments and ICD-11 diagnostic search.',
          eyebrow: 'Clinical', title: 'Faster, more precise assessments',
          lead: 'Set the right goals faster: AI-assisted initial assessments and a built-in ICD-11 diagnostic search.',
          deep: 'Run AI-assisted initial assessments and find diagnoses with the built-in ICD-11 search. Set the right goals from day one, with editable forms that adapt to each patient and organized documentation for the whole team.',
          points: [
            { t: 'AI initial assessment', d: 'Speeds up personalized care planning.' },
            { t: 'ICD-11 search', d: 'Find and record diagnoses without leaving the platform.' },
            { t: 'Editable forms', d: 'Adapt each assessment to the patient\'s reality.' },
          ],
          forWhom: 'For therapists and analysts who run initial assessments and need to define goals precisely and quickly.',
          roles: ['ABA therapists', 'Analysts', 'Clinical supervision'],
          sub: [
            { t: 'AI assessment', d: 'Speeds up the patient\'s initial assessment.' },
            { t: 'ICD-11 search', d: 'Diagnoses built into the platform.' },
            { t: 'Editable forms', d: 'Adapt each assessment to the case.' },
            { t: 'Goal plan', d: 'From diagnosis to plan, in one flow.' },
          ],
          benefits: ['Faster planning', 'Greater clinical precision', 'Organized documentation', 'Less manual work'],
          quote: 'I plan a new patient\'s care in far less time and with more confidence.',
          quoteRole: 'ABA Therapist · Children\'s center',
          ctaSub: 'We\'ll show you how to speed up your assessments.',
        },
        portal: {
          name: 'Family portal', short: 'Families see progress and receive activities for home.',
          eyebrow: 'Families', title: 'The family, inside the process',
          lead: 'A portal where parents see progress in real time, receive reports and activities, and message the specialist — with automatic alerts.',
          deep: 'Families stop being left out of the process. From their portal they see progress in real time, receive reports and home activities, and message the specialist — with automatic alerts. More engaged parents and better outcomes for the child.',
          points: [
            { t: 'Real-time progress', d: 'Families follow their child\'s progress whenever they want.' },
            { t: 'Activities for home', d: 'Reinforce therapy with recommended activities.' },
            { t: 'Messaging with the specialist', d: 'Close communication without losing clinical order.' },
          ],
          forWhom: 'For families who want to follow their child\'s progress and for the center seeking more adherence and better communication.',
          roles: ['Families and caregivers', 'Therapists', 'Management'],
          sub: [
            { t: 'Live progress', d: 'Patient progress in real time.' },
            { t: 'Home activities', d: 'Recommended reinforcement for parents.' },
            { t: 'Family reports', d: 'Clear, easy-to-understand summaries.' },
            { t: 'Alerts & messaging', d: 'Notifications and direct communication.' },
          ],
          benefits: ['More engaged families', 'Better adherence', 'Clear communication', 'Automatic alerts'],
          quote: 'Parents are more involved and at ease: they see their child\'s progress whenever they want.',
          quoteRole: 'Director · Therapy center',
          ctaSub: 'Book a demo of the family portal.',
        },
        comunicacion: {
          name: 'Internal communication', short: 'Internal team chat and Automatic alerts to families.',
          eyebrow: 'Communication', title: 'Your whole team and families, connected',
          lead: 'Internal chat across the clinical team and automatic Automatic alerts to families, without losing order or privacy.',
          deep: 'Leave scattered chats and improvised groups behind. Vanty ABA centralizes team communication and keeps families informed with automatic alerts — reminders, reports and important messages arrive on time, and everything stays organized inside the platform.',
          points: [
            { t: 'Internal chat', d: 'Team conversations by patient and by area.' },
            { t: 'Family notifications', d: 'Automatic WhatsApp alerts at the right moment.' },
            { t: 'All organized', d: 'Communication stays linked to the clinical record.' },
          ],
          forWhom: 'For teams who want to stop losing information in scattered chats and for families who want to stay informed without installing anything new.',
          roles: ['Clinical team', 'Front desk', 'Families'],
          sub: [
            { t: 'Chat per patient', d: 'Each case with its own conversation thread.' },
            { t: 'WhatsApp to families', d: 'Automatic reminders and alerts.' },
            { t: 'Role-based permissions', d: 'Everyone sees only what they should.' },
            { t: 'Unified history', d: 'Messages linked to the clinical file.' },
          ],
          benefits: ['Fewer misunderstandings', 'Informed families', 'Organized communication', 'Privacy by role'],
          quote: 'Families get WhatsApp alerts and the team stopped losing important messages.',
          quoteRole: 'Coordination · Therapy center',
          ctaSub: 'We\'ll show you how to organize your center\'s communication.',
        },
        videollamadas: {
          name: 'Video calls', short: 'High-quality remote sessions, inside the same platform.',
          eyebrow: 'Telehealth', title: 'Remote sessions, without leaving Vanty ABA',
          lead: 'Provide care remotely with high-quality video calls built into the platform — no external apps or scattered links.',
          deep: 'When the family can\'t make it, therapy doesn\'t stop. Run high-quality remote sessions from the same platform where you record, assess and report — everything stays connected to the patient\'s history, with no jumping between tools.',
          points: [
            { t: 'Built-in video call', d: 'Start the remote session from the patient\'s schedule.' },
            { t: 'High quality', d: 'Stable audio and video for a smooth session.' },
            { t: 'All in one place', d: 'Record and report without switching tools.' },
          ],
          forWhom: 'For centers serving families remotely or in distant areas, and for therapists who combine in-person and remote sessions.',
          roles: ['Therapists', 'Families', 'Management'],
          sub: [
            { t: 'Session from the schedule', d: 'One click to start the video call.' },
            { t: 'No external apps', d: 'Everything happens inside Vanty ABA.' },
            { t: 'Linked to the patient', d: 'The session stays in their history.' },
            { t: 'Live data capture', d: 'Take data while you provide care.' },
          ],
          benefits: ['More coverage', 'Fewer no-shows', 'No extra tools', 'Everything connected'],
          quote: 'I can serve families who live far away without them missing a single session.',
          quoteRole: 'ABA Therapist · Therapy center',
          ctaSub: 'Book a demo of the built-in video calls.',
        },
      },
    },
  },

  pt: {
    feat: {
      gridTitle: 'Cada função, a fundo',
      gridLead: 'Conheça em detalhe tudo o que o Vanty ABA faz pelo seu centro.',
      conocer: 'Ver detalhe', back: 'Voltar ao Vanty ABA',
      benefitsTitle: 'Benefícios', practiceTitle: 'Na prática',
      forWhomTitle: 'Para quem é?', subTitle: 'Tudo o que inclui',
      subLead: 'Funções pensadas para o dia a dia clínico.', ctaTitle: 'Vamos ver no seu centro',
      items: {
        aria: {
          name: 'ARIA · Copiloto IA', short: 'Assistentes de IA que geram notas, relatórios e alertas em segundos.',
          eyebrow: 'Inteligência clínica', title: 'ARIA, a IA clínica que trabalha pela sua equipe',
          lead: 'Mais que um chatbot: a ARIA é a inteligência clínica do Vanty ABA, treinada no fluxo real de um centro. Redige notas, organiza relatórios, revisa a documentação e antecipa o que importa — para devolver aos seus terapeutas as horas que o papelório tira.',
          deep: 'A ARIA aprende como o seu centro trabalha e assume a parte repetitiva do dia a dia clínico. Gera notas de sessão e relatórios prontos para supervisão em segundos, detecta lacunas antes que virem problema e sugere objetivos por domínio para cada paciente. Sua equipe recupera horas toda semana e mantém um padrão clínico impecável, sem esforço extra.',
          points: [
            { icon: 'fileText', t: 'Notas e relatórios em segundos', d: 'A ARIA transforma cada sessão em notas e relatórios clínicos completos na hora, prontos para supervisão.' },
            { icon: 'target', t: 'Objetivos sugeridos por domínio', d: 'Propõe e avalia objetivos ABA personalizados para cada paciente, a partir dos seus dados reais.' },
            { icon: 'activity', t: 'Padrões e alertas antecipados', d: 'Encontra tendências nos dados de sessão e avisa sobre riscos antes que aconteçam.' },
          ],
          forWhom: 'Para terapeutas e analistas que querem dedicar tempo aos pacientes e não ao papelório, e para a supervisão clínica que precisa de documentação confiável e sempre em dia.',
          roles: ['Terapeutas e especialistas', 'Analistas e supervisão', 'Direção clínica'],
          sub: [
            { icon: 'fileText', t: 'Notas clínicas automáticas', d: 'Suas sessões transformadas em notas e relatórios profissionais, sem escrever do zero.' },
            { icon: 'target', t: 'Objetivos sob medida do paciente', d: 'Sugestões e avaliação de objetivos ABA por domínio, baseadas em dados reais.' },
            { icon: 'shieldCheck', t: 'Controle de qualidade documental', d: 'A ARIA revisa sua documentação e avisa o que falta, para que nada passe batido.' },
            { icon: 'bookOpen', t: 'Seu conhecimento, sempre à mão', d: 'Uma base de conhecimento clínico que responde suas dúvidas na hora, quando você precisa.' },
          ],
          benefits: ['Recupere horas clínicas toda semana', 'Documentação impecável e consistente', 'Menos esgotamento para a sua equipe', 'Decisões clínicas com respaldo de dados'],
          quote: 'Eu passava horas escrevendo relatórios. Com a ARIA tenho em minutos e minha cabeça está onde deve: nos meus pacientes.',
          quoteRole: 'Analista ABA · Lima, Peru',
          ctaSub: 'Mostramos a ARIA trabalhando com o fluxo real do seu centro.',
        },
        analitica: {
          name: 'Analítica e relatórios', short: 'Gráficos de domínio por objetivo e alertas automáticos em ≥80%.',
          eyebrow: 'Dados clínicos', title: 'Analítica que se entende sozinha',
          lead: 'Gráficos de domínio por objetivo, gerados automaticamente a partir do registro de sessão, com alertas e resumos prontos para supervisão.',
          deep: 'Cada dado que você registra na sessão vira automaticamente gráficos claros por objetivo e domínio. Detecta estagnações a tempo, justifica decisões com evidência e chega a cada supervisão com tudo pronto, sem passar a noite montando planilhas.',
          points: [
            { t: 'Gráficos por objetivo e domínio', d: 'Veja o progresso de cada paciente sem montar planilhas.' },
            { t: 'Alertas automáticos', d: 'Avisos quando um objetivo atinge ≥80%, para decidir o próximo passo a tempo.' },
            { t: 'Relatórios prontos', d: 'Resumos claros para direção, famílias e supervisão clínica.' },
          ],
          forWhom: 'Para supervisores e direções que precisam ver o progresso clínico e operacional num olhar e decidir com dados, não com intuição.',
          roles: ['Supervisão clínica', 'Direção do centro', 'Analistas ABA'],
          sub: [
            { t: 'Gráficos por domínio', d: 'Progresso por objetivo, gerado automaticamente.' },
            { t: 'Alertas de metas', d: 'Avisos ao atingir ≥80% num objetivo.' },
            { t: 'Resumos de supervisão', d: 'Tudo pronto para cada reunião clínica.' },
            { t: 'Importação de dados', d: 'Traga seu histórico do Excel sem fricção.' },
          ],
          benefits: ['Visibilidade total do centro', 'Menos trabalho manual', 'Decisões mais rápidas', 'Importação do Excel'],
          quote: 'Finalmente vejo o progresso de cada criança num olhar, sem brigar com o Excel.',
          quoteRole: 'Supervisora clínica · Centro ABA',
          ctaSub: 'Agende uma demo e veja seus dados fazerem sentido.',
        },
        agenda: {
          name: 'Agenda e calendário', short: 'Sessões e consultas sincronizadas com Google e Outlook.',
          eyebrow: 'Agendamento', title: 'Agenda inteligente, sem conflitos',
          lead: 'Coordene sessões, terapeutas e salas num calendário claro, sincronizado com Google e Outlook.',
          deep: 'Coordene dezenas de sessões, terapeutas e salas sem conflitos nem buracos. A agenda sincroniza com Google e Outlook, envia lembretes automáticos e deixa as famílias reservarem com um link — menos ligações, menos faltas e uma semana que enfim fecha.',
          points: [
            { t: 'Sincronização Google e Outlook', d: 'Sua agenda sempre em dia em todas as ferramentas.' },
            { t: 'Visão por terapeuta e paciente', d: 'Organize a semana inteira do centro num olhar.' },
            { t: 'Link para reservar', d: 'As famílias marcam suas consultas com um link, sem ligações.' },
          ],
          forWhom: 'Para secretaria e coordenação que montam a semana do centro, e para famílias que querem reservar sem precisar ligar.',
          roles: ['Secretaria', 'Coordenação', 'Famílias'],
          sub: [
            { t: 'Calendário do centro', d: 'Sessões, terapeutas e salas numa só visão.' },
            { t: 'Sincronização', d: 'Conecta com Google Calendar e Outlook.' },
            { t: 'Reserva com link', d: 'As famílias agendam com um link.' },
            { t: 'Lembretes', d: 'Avisos automáticos para reduzir faltas.' },
          ],
          benefits: ['Menos faltas', 'Zero reservas duplicadas', 'Coordenação clara', 'Lembretes automáticos'],
          quote: 'Organizar a semana do centro deixou de ser dor de cabeça e passou a levar minutos.',
          quoteRole: 'Secretaria · Centro de terapias',
          ctaSub: 'Ajudamos a organizar a agenda de todo o seu centro.',
        },
        pagos: {
          name: 'Faturamento e pagamentos', short: 'Gerencie pagamentos, emita comprovantes e relatórios financeiros.',
          eyebrow: 'Finanças', title: 'Seus pagamentos, sob controle',
          lead: 'Gerencie os pagamentos do seu centro, emita comprovantes e obtenha relatórios financeiros claros, sem planilhas dispersas.',
          deep: 'Controle cada pagamento, emita comprovantes em segundos e veja a situação financeira do seu centro em tempo real. Menos inadimplência, contas claras e relatórios prontos para decidir, sem planilhas dispersas nem surpresas no fim do mês.',
          points: [
            { t: 'Controle de pagamentos', d: 'Registre e acompanhe os pagamentos de cada família.' },
            { t: 'Comprovantes', d: 'Emita comprovantes organizados em segundos.' },
            { t: 'Relatórios financeiros', d: 'Veja receitas e pendências para decidir melhor.' },
          ],
          forWhom: 'Para administração e direção que querem contas claras, menos inadimplência e relatórios financeiros sem esforço manual.',
          roles: ['Administração', 'Direção', 'Contabilidade'],
          sub: [
            { t: 'Registro de pagamentos', d: 'Acompanhamento por família e por paciente.' },
            { t: 'Comprovantes', d: 'Emissão organizada em segundos.' },
            { t: 'Extratos', d: 'Pendências e receitas sempre em dia.' },
            { t: 'Relatórios financeiros', d: 'Visão clara para decidir melhor.' },
          ],
          benefits: ['Menos inadimplência', 'Contas claras', 'Economia de tempo administrativo', 'Tudo num só lugar'],
          quote: 'As contas do centro estão claras e em dia, sem perseguir pagamentos em papelzinhos.',
          quoteRole: 'Administração · Centro ABA',
          ctaSub: 'Vamos conversar sobre organizar a parte financeira do seu centro.',
        },
        evaluaciones: {
          name: 'Avaliações + CID-11', short: 'Avaliações iniciais com IA e busca diagnóstica CID-11.',
          eyebrow: 'Clínico', title: 'Avaliações mais rápidas e precisas',
          lead: 'Defina os objetivos certos com mais rapidez: avaliações iniciais assistidas por IA e busca diagnóstica CID-11 integrada.',
          deep: 'Faça avaliações iniciais assistidas por IA e encontre diagnósticos com a busca CID-11 integrada. Defina os objetivos certos desde o primeiro dia, com fichas editáveis que se adaptam a cada paciente e documentação organizada para toda a equipe.',
          points: [
            { t: 'Avaliação inicial com IA', d: 'Acelera o planejamento do atendimento personalizado.' },
            { t: 'Busca CID-11', d: 'Encontre e registre diagnósticos sem sair da plataforma.' },
            { t: 'Fichas editáveis', d: 'Adapte cada avaliação à realidade do paciente.' },
          ],
          forWhom: 'Para terapeutas e analistas que realizam avaliações iniciais e precisam definir objetivos com precisão e rapidez.',
          roles: ['Terapeutas ABA', 'Analistas', 'Supervisão clínica'],
          sub: [
            { t: 'Avaliação com IA', d: 'Acelera a avaliação inicial do paciente.' },
            { t: 'Busca CID-11', d: 'Diagnósticos integrados na plataforma.' },
            { t: 'Fichas editáveis', d: 'Adapte cada avaliação ao caso.' },
            { t: 'Plano de objetivos', d: 'Do diagnóstico ao plano, num só fluxo.' },
          ],
          benefits: ['Planejamento mais rápido', 'Maior precisão clínica', 'Documentação organizada', 'Menos trabalho manual'],
          quote: 'Planejo o atendimento de um novo paciente em muito menos tempo e com mais segurança.',
          quoteRole: 'Terapeuta ABA · Centro infantil',
          ctaSub: 'Mostramos como agilizar suas avaliações.',
        },
        portal: {
          name: 'Portal familiar', short: 'As famílias veem o progresso e recebem atividades para casa.',
          eyebrow: 'Famílias', title: 'A família, dentro do processo',
          lead: 'Um portal onde os pais veem o progresso em tempo real, recebem relatórios e atividades, e conversam com o especialista — com avisos automáticos.',
          deep: 'As famílias deixam de ficar fora do processo. No portal veem o progresso em tempo real, recebem relatórios e atividades para casa, e conversam com o especialista — com avisos automáticos. Mais engajamento dos pais e melhores resultados para a criança.',
          points: [
            { t: 'Progresso em tempo real', d: 'As famílias acompanham os avanços do filho quando quiserem.' },
            { t: 'Atividades para casa', d: 'Reforce a terapia com atividades recomendadas.' },
            { t: 'Mensagens com o especialista', d: 'Comunicação próxima sem perder a ordem clínica.' },
          ],
          forWhom: 'Para famílias que querem acompanhar o progresso do filho e para o centro que busca mais adesão e melhor comunicação.',
          roles: ['Famílias e cuidadores', 'Terapeutas', 'Direção'],
          sub: [
            { t: 'Progresso ao vivo', d: 'Avanços do paciente em tempo real.' },
            { t: 'Atividades em casa', d: 'Reforço recomendado para os pais.' },
            { t: 'Relatórios para famílias', d: 'Resumos claros e compreensíveis.' },
            { t: 'Avisos e mensagens', d: 'Notificações e comunicação direta.' },
          ],
          benefits: ['Famílias mais engajadas', 'Melhor adesão', 'Comunicação clara', 'Avisos automáticos'],
          quote: 'Os pais estão mais envolvidos e tranquilos: veem os avanços do filho quando querem.',
          quoteRole: 'Diretora · Centro de terapias',
          ctaSub: 'Agende uma demo do portal familiar.',
        },
        comunicacion: {
          name: 'Comunicação interna', short: 'Chat interno da equipe e notificações às famílias.',
          eyebrow: 'Comunicação', title: 'Toda a equipe e as famílias, conectadas',
          lead: 'Chat interno entre a equipe clínica e notificações automáticas às famílias por WhatsApp, sem perder a ordem nem a privacidade.',
          deep: 'Deixe os chats soltos e os grupos improvisados. O Vanty ABA centraliza a comunicação da equipe e mantém as famílias informadas com avisos automáticos — lembretes, relatórios e mensagens importantes chegam a tempo, e tudo fica organizado dentro da plataforma.',
          points: [
            { t: 'Chat interno', d: 'Conversas da equipe por paciente e por área.' },
            { t: 'Notificações às famílias', d: 'Avisos automáticos por WhatsApp na hora certa.' },
            { t: 'Tudo organizado', d: 'A comunicação fica ligada ao histórico clínico.' },
          ],
          forWhom: 'Para equipes que querem parar de perder informação em chats dispersos e para famílias que querem ficar por dentro sem instalar nada novo.',
          roles: ['Equipe clínica', 'Secretaria', 'Famílias'],
          sub: [
            { t: 'Chat por paciente', d: 'Cada caso com seu próprio fio de conversa.' },
            { t: 'WhatsApp às famílias', d: 'Lembretes e avisos automáticos.' },
            { t: 'Permissões por papel', d: 'Cada um vê apenas o que lhe cabe.' },
            { t: 'Histórico unificado', d: 'Mensagens ligadas ao prontuário clínico.' },
          ],
          benefits: ['Menos mal-entendidos', 'Famílias informadas', 'Comunicação organizada', 'Privacidade por papel'],
          quote: 'As famílias recebem os avisos automáticos e a equipe parou de perder mensagens importantes.',
          quoteRole: 'Coordenação · Centro de terapias',
          ctaSub: 'Mostramos como organizar a comunicação do seu centro.',
        },
        videollamadas: {
          name: 'Videochamadas', short: 'Sessões remotas em alta qualidade, dentro da mesma plataforma.',
          eyebrow: 'Telessaúde', title: 'Sessões remotas, sem sair do Vanty ABA',
          lead: 'Atenda à distância com videochamadas em alta qualidade integradas à plataforma — sem apps externos nem links dispersos.',
          deep: 'Quando a família não pode comparecer, a terapia não para. Realize sessões remotas em alta qualidade na mesma plataforma onde você registra, avalia e relata — tudo fica conectado ao histórico do paciente, sem pular entre ferramentas.',
          points: [
            { t: 'Videochamada integrada', d: 'Inicie a sessão remota a partir da agenda do paciente.' },
            { t: 'Alta qualidade', d: 'Áudio e vídeo estáveis para uma sessão fluida.' },
            { t: 'Tudo num só lugar', d: 'Registre e relate sem trocar de ferramenta.' },
          ],
          forWhom: 'Para centros que atendem famílias à distância ou em áreas afastadas, e para terapeutas que combinam sessões presenciais e remotas.',
          roles: ['Terapeutas', 'Famílias', 'Direção'],
          sub: [
            { t: 'Sessão a partir da agenda', d: 'Um clique para iniciar a videochamada.' },
            { t: 'Sem apps externos', d: 'Tudo acontece dentro do Vanty ABA.' },
            { t: 'Ligada ao paciente', d: 'A sessão fica no histórico dele.' },
            { t: 'Registro ao vivo', d: 'Colete dados enquanto atende.' },
          ],
          benefits: ['Mais cobertura', 'Menos faltas', 'Sem ferramentas extras', 'Tudo conectado'],
          quote: 'Consigo atender famílias que moram longe sem que percam uma sessão sequer.',
          quoteRole: 'Terapeuta ABA · Centro de terapias',
          ctaSub: 'Agende uma demo das videochamadas integradas.',
        },
      },
    },
  },

  fr: {
    feat: {
      gridTitle: 'Chaque fonction, en détail',
      gridLead: 'Découvrez en détail tout ce que Vanty ABA fait pour votre centre.',
      conocer: 'Voir le détail', back: 'Retour à Vanty ABA',
      benefitsTitle: 'Avantages', practiceTitle: 'En pratique',
      forWhomTitle: 'Pour qui ?', subTitle: 'Tout ce qu\'il inclut',
      subLead: 'Des fonctions pensées pour le quotidien clinique.', ctaTitle: 'Voyons-le dans votre centre',
      items: {
        aria: {
          name: 'ARIA · Copilote IA', short: 'Des assistants IA qui génèrent notes, rapports et alertes en quelques secondes.',
          eyebrow: 'Intelligence clinique', title: 'ARIA, l\'IA clinique qui travaille pour votre équipe',
          lead: 'Plus qu\'un chatbot : ARIA est l\'intelligence clinique de Vanty ABA, entraînée sur le flux réel d\'un centre. Elle rédige les notes, organise les rapports, vérifie la documentation et anticipe l\'essentiel — pour rendre à vos thérapeutes les heures que la paperasse leur prend.',
          deep: 'ARIA apprend comment votre centre fonctionne et prend en charge la partie répétitive du quotidien clinique. Elle génère des notes de séance et des rapports prêts pour la supervision en quelques secondes, repère les lacunes avant qu\'elles ne deviennent un problème et suggère des objectifs par domaine pour chaque patient. Votre équipe récupère des heures chaque semaine et maintient un standard clinique impeccable, sans effort supplémentaire.',
          points: [
            { icon: 'fileText', t: 'Notes et rapports en quelques secondes', d: 'ARIA transforme chaque séance en notes et rapports cliniques complets à l\'instant, prêts pour la supervision.' },
            { icon: 'target', t: 'Objectifs suggérés par domaine', d: 'Propose et évalue des objectifs ABA personnalisés pour chaque patient, à partir de ses données réelles.' },
            { icon: 'activity', t: 'Tendances et alertes précoces', d: 'Repère les tendances dans les données de séance et vous alerte des risques avant qu\'ils n\'arrivent.' },
          ],
          forWhom: 'Pour les thérapeutes et analystes qui veulent consacrer leur temps aux patients et non à la paperasse, et pour la supervision clinique qui a besoin d\'une documentation fiable et toujours à jour.',
          roles: ['Thérapeutes et spécialistes', 'Analystes et supervision', 'Direction clinique'],
          sub: [
            { icon: 'fileText', t: 'Notes cliniques automatiques', d: 'Vos séances transformées en notes et rapports professionnels, sans repartir de zéro.' },
            { icon: 'target', t: 'Objectifs adaptés au patient', d: 'Suggestions et évaluation d\'objectifs ABA par domaine, basées sur des données réelles.' },
            { icon: 'shieldCheck', t: 'Contrôle qualité de la documentation', d: 'ARIA vérifie votre documentation et signale ce qui manque, pour que rien n\'échappe.' },
            { icon: 'bookOpen', t: 'Votre savoir, toujours à portée', d: 'Une base de connaissances clinique qui répond à vos questions à l\'instant, quand vous en avez besoin.' },
          ],
          benefits: ['Récupérez des heures cliniques chaque semaine', 'Une documentation impeccable et cohérente', 'Moins d\'épuisement pour votre équipe', 'Des décisions cliniques appuyées par les données'],
          quote: 'Je passais des heures à rédiger des rapports. Avec ARIA je les ai en quelques minutes et ma tête est là où elle doit être : sur mes patients.',
          quoteRole: 'Analyste ABA · Lima, Pérou',
          ctaSub: 'Nous vous montrons ARIA en action avec le flux réel de votre centre.',
        },
        analitica: {
          name: 'Analytique et rapports', short: 'Graphiques de domaine par objectif et alertes automatiques à ≥80%.',
          eyebrow: 'Données cliniques', title: 'Une analytique qui se comprend seule',
          lead: 'Des graphiques de domaine par objectif, générés automatiquement à partir des séances, avec alertes et résumés prêts pour la supervision.',
          deep: 'Chaque donnée saisie en séance devient automatiquement des graphiques clairs par objectif et domaine. Repérez les stagnations à temps, justifiez vos décisions avec des preuves et arrivez à chaque supervision avec tout prêt, sans passer la nuit sur des tableurs.',
          points: [
            { t: 'Graphiques par objectif et domaine', d: 'Visualisez les progrès de chaque patient sans tableurs.' },
            { t: 'Alertes automatiques', d: 'Avis lorsqu\'un objectif atteint ≥80%, pour décider à temps.' },
            { t: 'Rapports prêts', d: 'Des résumés clairs pour la direction, les familles et la supervision.' },
          ],
          forWhom: 'Pour les superviseurs et directions qui doivent voir les progrès cliniques et opérationnels d\'un coup d\'œil et décider avec des données, pas à l\'intuition.',
          roles: ['Supervision clinique', 'Direction du centre', 'Analystes ABA'],
          sub: [
            { t: 'Graphiques par domaine', d: 'Progrès par objectif, générés automatiquement.' },
            { t: 'Alertes d\'objectifs', d: 'Avis lorsqu\'un objectif atteint ≥80%.' },
            { t: 'Résumés de supervision', d: 'Tout prêt pour chaque réunion clinique.' },
            { t: 'Import de données', d: 'Importez votre historique depuis Excel sans friction.' },
          ],
          benefits: ['Visibilité totale du centre', 'Moins de travail manuel', 'Décisions plus rapides', 'Import depuis Excel'],
          quote: 'Je vois enfin les progrès de chaque enfant d\'un coup d\'œil, sans me battre avec Excel.',
          quoteRole: 'Superviseure clinique · Centre ABA',
          ctaSub: 'Réservez une démo et voyez vos données prendre sens.',
        },
        agenda: {
          name: 'Agenda et calendrier', short: 'Séances et rendez-vous synchronisés avec Google et Outlook.',
          eyebrow: 'Planification', title: 'Un agenda intelligent, sans conflits',
          lead: 'Coordonnez séances, thérapeutes et salles dans un calendrier clair, synchronisé avec Google et Outlook.',
          deep: 'Coordonnez des dizaines de séances, thérapeutes et salles sans conflits ni trous. L\'agenda se synchronise avec Google et Outlook, envoie des rappels automatiques et laisse les familles réserver via un lien — moins d\'appels, moins d\'absences et une semaine qui tient enfin debout.',
          points: [
            { t: 'Synchronisation Google et Outlook', d: 'Votre agenda toujours à jour dans tous vos outils.' },
            { t: 'Vue par thérapeute et patient', d: 'Organisez la semaine complète du centre d\'un coup d\'œil.' },
            { t: 'Lien de réservation', d: 'Les familles réservent leurs rendez-vous via un lien, sans appels.' },
          ],
          forWhom: 'Pour le secrétariat et la coordination qui construisent la semaine du centre, et pour les familles qui veulent réserver sans appeler.',
          roles: ['Secrétariat', 'Coordination', 'Familles'],
          sub: [
            { t: 'Calendrier du centre', d: 'Séances, thérapeutes et salles dans une seule vue.' },
            { t: 'Synchronisation', d: 'Connecté à Google Calendar et Outlook.' },
            { t: 'Réservation par lien', d: 'Les familles réservent via un lien.' },
            { t: 'Rappels', d: 'Avis automatiques pour réduire les absences.' },
          ],
          benefits: ['Moins d\'absences', 'Zéro double réservation', 'Coordination claire', 'Rappels automatiques'],
          quote: 'Organiser la semaine du centre est passé d\'un casse-tête à quelques minutes.',
          quoteRole: 'Secrétariat · Centre de thérapie',
          ctaSub: 'Nous vous aidons à organiser l\'agenda de tout votre centre.',
        },
        pagos: {
          name: 'Facturation et paiements', short: 'Gérez les paiements, émettez des reçus et des rapports financiers.',
          eyebrow: 'Finances', title: 'Vos paiements, sous contrôle',
          lead: 'Gérez les paiements de votre centre, émettez des reçus et obtenez des rapports financiers clairs, sans tableurs dispersés.',
          deep: 'Suivez chaque paiement, émettez des reçus en quelques secondes et voyez l\'état financier de votre centre en temps réel. Moins d\'impayés, des comptes clairs et des rapports prêts pour décider, sans tableurs dispersés ni surprises en fin de mois.',
          points: [
            { t: 'Contrôle des paiements', d: 'Enregistrez et suivez les paiements de chaque famille.' },
            { t: 'Reçus', d: 'Émettez des reçus ordonnés en quelques secondes.' },
            { t: 'Rapports financiers', d: 'Visualisez revenus et impayés pour mieux décider.' },
          ],
          forWhom: 'Pour l\'administration et la direction qui veulent des comptes clairs, moins d\'impayés et des rapports financiers sans effort manuel.',
          roles: ['Administration', 'Direction', 'Comptabilité'],
          sub: [
            { t: 'Suivi des paiements', d: 'Suivi par famille et par patient.' },
            { t: 'Reçus', d: 'Émission ordonnée en quelques secondes.' },
            { t: 'Relevés', d: 'Impayés et revenus toujours à jour.' },
            { t: 'Rapports financiers', d: 'Une vision claire pour mieux décider.' },
          ],
          benefits: ['Moins d\'impayés', 'Comptes clairs', 'Temps administratif gagné', 'Tout au même endroit'],
          quote: 'Les comptes du centre sont clairs et à jour, sans courir après les paiements sur des bouts de papier.',
          quoteRole: 'Administration · Centre ABA',
          ctaSub: 'Parlons de l\'organisation financière de votre centre.',
        },
        evaluaciones: {
          name: 'Évaluations + CIM-11', short: 'Évaluations initiales avec IA et recherche diagnostique CIM-11.',
          eyebrow: 'Clinique', title: 'Des évaluations plus rapides et précises',
          lead: 'Définissez les bons objectifs plus vite : évaluations initiales assistées par IA et recherche diagnostique CIM-11 intégrée.',
          deep: 'Réalisez des évaluations initiales assistées par IA et trouvez des diagnostics avec la recherche CIM-11 intégrée. Définissez les bons objectifs dès le premier jour, avec des fiches modifiables qui s\'adaptent à chaque patient et une documentation ordonnée pour toute l\'équipe.',
          points: [
            { t: 'Évaluation initiale avec IA', d: 'Accélère la planification des soins personnalisés.' },
            { t: 'Recherche CIM-11', d: 'Trouvez et enregistrez des diagnostics sans quitter la plateforme.' },
            { t: 'Fiches modifiables', d: 'Adaptez chaque évaluation à la réalité du patient.' },
          ],
          forWhom: 'Pour les thérapeutes et analystes qui réalisent des évaluations initiales et doivent définir des objectifs avec précision et rapidité.',
          roles: ['Thérapeutes ABA', 'Analystes', 'Supervision clinique'],
          sub: [
            { t: 'Évaluation avec IA', d: 'Accélère l\'évaluation initiale du patient.' },
            { t: 'Recherche CIM-11', d: 'Diagnostics intégrés à la plateforme.' },
            { t: 'Fiches modifiables', d: 'Adaptez chaque évaluation au cas.' },
            { t: 'Plan d\'objectifs', d: 'Du diagnostic au plan, en un seul flux.' },
          ],
          benefits: ['Planification plus rapide', 'Plus de précision clinique', 'Documentation ordonnée', 'Moins de travail manuel'],
          quote: 'Je planifie la prise en charge d\'un nouveau patient en bien moins de temps et avec plus de confiance.',
          quoteRole: 'Thérapeute ABA · Centre pour enfants',
          ctaSub: 'Nous vous montrons comment accélérer vos évaluations.',
        },
        portal: {
          name: 'Portail familial', short: 'Les familles voient les progrès et reçoivent des activités à la maison.',
          eyebrow: 'Familles', title: 'La famille, au cœur du processus',
          lead: 'Un portail où les parents voient les progrès en temps réel, reçoivent rapports et activités, et échangent avec le spécialiste — avec des alertes automatiques.',
          deep: 'Les familles ne restent plus à l\'écart du processus. Depuis leur portail, elles voient les progrès en temps réel, reçoivent rapports et activités à la maison, et échangent avec le spécialiste — avec des alertes automatiques. Des parents plus impliqués et de meilleurs résultats pour l\'enfant.',
          points: [
            { t: 'Progrès en temps réel', d: 'Les familles suivent les progrès de leur enfant quand elles veulent.' },
            { t: 'Activités à la maison', d: 'Renforcez la thérapie avec des activités recommandées.' },
            { t: 'Messagerie avec le spécialiste', d: 'Une communication proche sans perdre l\'ordre clinique.' },
          ],
          forWhom: 'Pour les familles qui veulent suivre les progrès de leur enfant et pour le centre qui cherche plus d\'adhésion et une meilleure communication.',
          roles: ['Familles et aidants', 'Thérapeutes', 'Direction'],
          sub: [
            { t: 'Progrès en direct', d: 'Progrès du patient en temps réel.' },
            { t: 'Activités à la maison', d: 'Renforcement recommandé pour les parents.' },
            { t: 'Rapports pour les familles', d: 'Des résumés clairs et compréhensibles.' },
            { t: 'Alertes et messagerie', d: 'Notifications et communication directe.' },
          ],
          benefits: ['Familles plus impliquées', 'Meilleure adhésion', 'Communication claire', 'Alertes automatiques'],
          quote: 'Les parents sont plus impliqués et rassurés : ils voient les progrès de leur enfant quand ils veulent.',
          quoteRole: 'Directrice · Centre de thérapie',
          ctaSub: 'Réservez une démo du portail familial.',
        },
        comunicacion: {
          name: 'Internal communication', short: 'Chat interne de l\'équipe et notifications aux familles.',
          eyebrow: 'Communication', title: 'Toute l\'équipe et les familles, connectées',
          lead: 'Un chat interne entre l\'équipe clinique et des notifications automatiques aux familles par WhatsApp, sans perdre l\'ordre ni la confidentialité.',
          deep: 'Finis les chats éparpillés et les groupes improvisés. Vanty ABA centralise la communication de l\'équipe et tient les familles informées avec des alertes automatiques — rappels, rapports et messages importants arrivent à temps, et tout reste ordonné dans la plateforme.',
          points: [
            { t: 'Chat interne', d: 'Conversations de l\'équipe par patient et par domaine.' },
            { t: 'Notifications aux familles', d: 'Alertes WhatsApp automatiques au bon moment.' },
            { t: 'Tout ordonné', d: 'La communication reste liée au dossier clinique.' },
          ],
          forWhom: 'Pour les équipes qui veulent arrêter de perdre des informations dans des chats éparpillés et pour les familles qui veulent rester informées sans rien installer de nouveau.',
          roles: ['Équipe clinique', 'Secrétariat', 'Familles'],
          sub: [
            { t: 'Chat par patient', d: 'Chaque cas avec son fil de conversation.' },
            { t: 'WhatsApp aux familles', d: 'Rappels et alertes automatiques.' },
            { t: 'Permissions par rôle', d: 'Chacun ne voit que ce qui le concerne.' },
            { t: 'Historique unifié', d: 'Messages liés au dossier clinique.' },
          ],
          benefits: ['Moins de malentendus', 'Familles informées', 'Communication ordonnée', 'Confidentialité par rôle'],
          quote: 'Les familles reçoivent les alertes WhatsApp et l\'équipe ne perd plus de messages importants.',
          quoteRole: 'Coordination · Centre de thérapie',
          ctaSub: 'Nous vous montrons comment organiser la communication de votre centre.',
        },
        videollamadas: {
          name: 'Appels vidéo', short: 'Séances à distance en haute qualité, dans la même plateforme.',
          eyebrow: 'Télésanté', title: 'Des séances à distance, sans quitter Vanty ABA',
          lead: 'Proposez des soins à distance avec des appels vidéo en haute qualité intégrés à la plateforme — sans applis externes ni liens éparpillés.',
          deep: 'Quand la famille ne peut pas venir, la thérapie ne s\'arrête pas. Réalisez des séances à distance en haute qualité depuis la plateforme où vous enregistrez, évaluez et faites vos rapports — tout reste connecté à l\'historique du patient, sans passer d\'un outil à l\'autre.',
          points: [
            { t: 'Appel vidéo intégré', d: 'Lancez la séance à distance depuis l\'agenda du patient.' },
            { t: 'Haute qualité', d: 'Audio et vidéo stables pour une séance fluide.' },
            { t: 'Tout au même endroit', d: 'Enregistrez et rapportez sans changer d\'outil.' },
          ],
          forWhom: 'Pour les centres qui suivent des familles à distance ou en zones éloignées, et pour les thérapeutes qui combinent séances en présentiel et à distance.',
          roles: ['Thérapeutes', 'Familles', 'Direction'],
          sub: [
            { t: 'Séance depuis l\'agenda', d: 'Un clic pour lancer l\'appel vidéo.' },
            { t: 'Sans applis externes', d: 'Tout se passe dans Vanty ABA.' },
            { t: 'Liée au patient', d: 'La séance reste dans son historique.' },
            { t: 'Saisie en direct', d: 'Prenez des données pendant la séance.' },
          ],
          benefits: ['Plus de couverture', 'Moins d\'absences', 'Aucun outil supplémentaire', 'Tout connecté'],
          quote: 'Je peux suivre des familles qui vivent loin sans qu\'elles manquent une seule séance.',
          quoteRole: 'Thérapeute ABA · Centre de thérapie',
          ctaSub: 'Réservez une démo des appels vidéo intégrés.',
        },
      },
    },
  },
}
